version: "3.7"
services:
  animals:
    build: .
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - /home/node/app/node_modules
      - ./:/home/node/app
    command: "npm run start"
    ports:
      - "8000:3000"