version: "3.7"
services:
  animals:
    image: nginx:stable-alpine
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./build/:/var/www/html/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"